# This file was generated by GoReleaser. DO NOT EDIT.
cask "lfm-cli" do
  version "1.6.3"

  on_macos do
    on_arm do
      sha256 "e89e830ed188f82b866c20d616c01708bc94182f47f7e3544f03f916eaec062f"
      url "https://github.com/twangodev/lfm-cli/releases/download/v#{version}/lfm-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/twangodev/lfm-cli/"
    end
    on_intel do
      sha256 "91057c86c79f95cff036266a847da02fa6a981b6f2d5242b33b7c6366063dda0"
      url "https://github.com/twangodev/lfm-cli/releases/download/v#{version}/lfm-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/twangodev/lfm-cli/"
    end
  end
  on_linux do
    on_arm do
      sha256 "06a42e0db5f8b6786f5aefa873c4c7ccabfea0bf55c7be10098470e8d00b3a34"
      url "https://github.com/twangodev/lfm-cli/releases/download/v#{version}/lfm-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/twangodev/lfm-cli/"
    end
    on_intel do
      sha256 "d29904c10c2f604ccbb1913400aa7cf4e0811403e4584e7892cb5c223b6ae93d"
      url "https://github.com/twangodev/lfm-cli/releases/download/v#{version}/lfm-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/twangodev/lfm-cli/"
    end
  end

  name "lfm-cli"
  desc "Show your Last.FM scrobbles on Discord"
  homepage "https://github.com/twangodev/lfm-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lfm-cli"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lfm-cli"]
    end
  end

  # No zap stanza required
end
