# This file was generated by GoReleaser. DO NOT EDIT.
cask "lfm-cli" do
  version "1.6.0"

  on_macos do
    on_intel do
      sha256 "64082122e220edde647fe69ccfc63ffabe870e83bfdf5d7bff88593dc740bae5"
      url "https://github.com/twangodev/lfm-cli/releases/download/v#{version}/lfm-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/twangodev/lfm-cli/"
    end
    on_arm do
      sha256 "061c751f944f8487aea83126f81f5af769930fc2e8d77078eba00c4be7267207"
      url "https://github.com/twangodev/lfm-cli/releases/download/v#{version}/lfm-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/twangodev/lfm-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "6d3d230152976dd29bdd6be12b88fc23e635216585c3d4437370364d43829941"
      url "https://github.com/twangodev/lfm-cli/releases/download/v#{version}/lfm-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/twangodev/lfm-cli/"
    end
    on_arm do
      sha256 "ce9411c8e34009739bbff44ccd9bfb3487a34e91a36dd64583f9242156a8d566"
      url "https://github.com/twangodev/lfm-cli/releases/download/v#{version}/lfm-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/twangodev/lfm-cli/"
    end
  end

  name "lfm-cli"
  desc "Show your Last.FM scrobbles on Discord."
  homepage "https://github.com/twangodev/lfm-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lfm-cli"

  # No zap stanza required

end
