# This file was generated by GoReleaser. DO NOT EDIT.
cask "lfm-cli" do
  version "1.6.2"

  on_macos do
    on_intel do
      sha256 "be2ec0ce7d99ddcb59c9bf47f2473bef696cf0b12346f00e37e393a1d3e1bbc5"
      url "https://github.com/twangodev/lfm-cli/releases/download/v#{version}/lfm-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/twangodev/lfm-cli/"
    end
    on_arm do
      sha256 "52c9d3b73a457a77184126ce30facdb16b54620b8e63ba8f4aedab2e7239e3a8"
      url "https://github.com/twangodev/lfm-cli/releases/download/v#{version}/lfm-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/twangodev/lfm-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "ab6d72e2bd9e3938fc19ff68b76a638ef4e21868aab43cee3f9d3e6ccd88fcef"
      url "https://github.com/twangodev/lfm-cli/releases/download/v#{version}/lfm-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/twangodev/lfm-cli/"
    end
    on_arm do
      sha256 "c9ce732e06933bd855c2fa0be1354fca8d5266470b98366cd7605698fd9e079f"
      url "https://github.com/twangodev/lfm-cli/releases/download/v#{version}/lfm-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/twangodev/lfm-cli/"
    end
  end

  name "lfm-cli"
  desc "Show your Last.FM scrobbles on Discord"
  homepage "https://github.com/twangodev/lfm-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lfm-cli"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lfm-cli"]
    end
  end

  # No zap stanza required

end
